apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vulnforge.fullname" . }}-config
  labels:
    {{- include "vulnforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  config.yaml: |
{{ toYaml .Values.config | nindent 4 }}
