apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulnforge.fullname" . }}-api
  labels:
    {{- include "vulnforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "vulnforge.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http

{{- if .Values.web.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulnforge.fullname" . }}-web
  labels:
    {{- include "vulnforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "vulnforge.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
{{- end }}
